# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Plucene-SearchEngine
version:      1.1
version_from: lib/Plucene/SearchEngine/Index.pm
installdirs:  site
requires:
    Date::Parse:                   0
    File::Basename:                0
    File::MMagic:                  0
    HTML::TreeBuilder:             0
    Lucene::QueryParser:           0
    LWP:                           0
    Module::Pluggable:             0
    Plucene:                       1.17
    Text::Context:                 0
    Time::Piece:                   0
    UNIVERSAL::moniker:            0
    UNIVERSAL::require:            0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
